CrawlerName: Name-For-This-Crawler
CrawlInterval: 1                    # Update every 1s (Default: 1)
Miners:                             # List of Miners
  - MinerName: S19Miner1            # Unique name of miner
    Host: 192.168.1.2               # IP/Address of the miner
    Port: 4028                      # Port of the miner's CGMiner RPC API
    Model:  X19                     # Miner model type. refer to README.md for supported list
  - MinerName: S19Miner2
    Host: someminer1.example.com
    Port: 4028
    Model:  X19
Redis:
  Host: localhost                   # IP/Address of Redis DB
  Port: 6379                        # Port of Redis DB
  Username:                         # Username for Redis
  Password:                         # Password for Redis
  SelectedDatabase: 1               # The Selected Database ID. (Default: 1)
